version: 2
jobs:
  MacOS:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-spm-deps-{{ checksum "Package.resolved" }}
      - run:
          name: Install CMySQL and CTLS
          command: |
            brew tap vapor/homebrew-tap
            brew install cmysql
            brew install ctls
      - run:
          name: Build and Run Tests
          no_output_timeout: 1800
          command: |
            swift test -Xswiftc -DNOJSON
      - save_cache:
          key: v1-spm-deps-{{ checksum "Package.resolved" }}
          paths:
            - .build
  Linux:
    docker:
      - image: brettrtoomey/vapor-ci:0.0.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-spm-deps-{{ checksum "Package.resolved" }}
      - run:
          name: Copy Resolved Package
          command: cp Package.resolved res
      - run:
          name: Build and Run Tests
          no_output_timeout: 1800
          command: |
            swift test -Xswiftc -DNOJSON
      - run:
          name: Restoring Resolved Package
          command: mv res Package.resolved
      - save_cache:
          key: v2-spm-deps-{{ checksum "Package.resolved" }}
          paths:
            - .build
workflows:
  version: 2
  build-and-test:
    jobs:
      - MacOS
      - Linux
experimental:
  notify:
    branches:
      only:
        - master
        - develop
