version: 2
jobs:
  swiftlint:
    docker:
      - image: dantoml/swiftlint:latest
    steps:
      - checkout
      - run: swiftlint lint --reporter junit | tee result.xml
      - store_artifacts:
          path: result.xml
      - store_test_results:
          path: result.xml
  MacOS:
    macos:
      xcode: "10.2.1"
    steps:
      - checkout
      - restore_cache:
          keys:
            - macos-v1-spm-deps-{{ checksum "Package.resolved" }}
      - run:
          name: Install dependencies
          command: |
            export HOMEBREW_NO_AUTO_UPDATE=1
            brew tap vapor/homebrew-tap
            brew install cmysql
            brew install ctls
            brew install libressl
            brew install cstack
      - run:
          name: Build and Run Tests
          no_output_timeout: 1800
          command: |
            swift test -Xswiftc -DNOJSON
      - save_cache:
          key: macos-v1-spm-deps-{{ checksum "Package.resolved" }}
          paths:
            - .build
  Linux:
    docker:
      - image: nodesvapor/vapor-ci:swift-5.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - linux-v1-spm-deps-{{ checksum "Package.resolved" }}
      - run:
          name: Copy Resolved Package
          command: cp Package.resolved res
      - run:
          name: Build and Run Tests
          no_output_timeout: 1800
          command: |
            swift test -Xswiftc -DNOJSON
      - run:
          name: Restoring Resolved Package
          command: mv res Package.resolved
      - save_cache:
          key: linux-v1-spm-deps-{{ checksum "Package.resolved" }}
          paths:
            - .build
workflows:
  version: 2
  build-and-test:
    jobs:
      - swiftlint
      - MacOS
      - Linux
experimental:
  notify:
    branches:
      only:
        - master
        - develop
