version: 2
jobs:
  MacOS:
    macos:
      xcode: "9.4.0"
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-spm-deps-{{ checksum "Package.resolved" }}
      - run:
          name: Install CMySQL and CTLS
          # A specific version of MySQL (5.7.22) is being installed due to MySQL 8 issues with Vapor 2
          command: |
            brew tap vapor/homebrew-tap
            brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/a340bfac3b7abff408a6b6fe6fdc39a38ab94871/Formula/mysql.rb
            brew install cmysql
            brew install ctls
            brew install cstack
            brew switch mysql 5.7.22
      - run:
          name: Build and Run Tests
          no_output_timeout: 1800
          command: |
            swift test -Xswiftc -DNOJSON
      - save_cache:
          key: v1-spm-deps-{{ checksum "Package.resolved" }}
          paths:
            - .build
  Linux:
    docker:
      - image: nodesvapor/vapor-ci:swift-4.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-spm-deps-{{ checksum "Package.resolved" }}
      - run:
          name: Copy Resolved Package
          command: cp Package.resolved res
      - run:
          name: Build and Run Tests
          no_output_timeout: 1800
          command: |
            swift test -Xswiftc -DNOJSON
      - run:
          name: Restoring Resolved Package
          command: mv res Package.resolved
      - save_cache:
          key: v2-spm-deps-{{ checksum "Package.resolved" }}
          paths:
            - .build
workflows:
  version: 2
  build-and-test:
    jobs:
      - MacOS
      - Linux
experimental:
  notify:
    branches:
      only:
        - master
        - develop
