name: test
on:
  pull_request:
  push:
    branches:
    - develop
jobs:
  vapor_macos:
    runs-on: macos-latest
    steps:
    - name: Select latest available Xcode
      uses: maxim-lobanov/setup-xcode@1.0
      with:
        xcode-version: latest
    - name: Check out code
      uses: actions/checkout@v2
    - name: Run tests with Thread Sanitizer
      run: xcrun swift test --enable-test-discovery --sanitize=thread
  vapor_bionic:
    container: 
      image: vapor/swift:5.2-bionic
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Run tests with Thread Sanitizer
      run: swift test --enable-test-discovery --sanitize=thread
