name: test
on:
  pull_request:
  workflow_dispatch:
jobs:
  vapor_focal:
    container: 
      image: swift:5.5-focal
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: swift test --sanitize=thread
